# @package _global_

fps: 30

env:
  name: real_world
  task: null
  state_dim: 6
  action_dim: 6
  fps: ${fps}
  device: mps
  
  wrapper:
    crop_params_dict:
      observation.images.laptop: [58, 89, 357, 455]
      observation.images.phone: [3, 4, 471, 633]
    resize_size: [128, 128]
    control_time_s: 20
    reset_follower_pos: true
    use_relative_joint_positions: true
    reset_time_s: 5
    display_cameras: false
    delta_action: 0.1
    joint_masking_action_space: [1, 1, 1, 1, 0, 0] # disable wrist and gripper

  reward_classifier:
    pretrained_path: outputs/classifier/checkpoints/best/pretrained_model
    config_path: lerobot/configs/policy/hilserl_classifier.yaml
    